name: Track MD Changes
on:
  push:
    paths:
      - '**.md'
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          echo "检测到 .md 文件变更！"
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -d '{"event_type":"md_changes"}' \
            "https://api.github.com/repos/MAA1999/M9A-WEB/dispatches"
